version: '3.3'
services:
  app_db:
    container_name: app_db
    build: db
    environment:
      - POSTGRES_DB=carto_test
      - POSTGRES_USER=carto_test
      - POSTGRES_PASSWORD=carto_test
    ports:
      - 5432:5432
